ModTarget = "Enemy.HellfireImp"

[Stats]
Health = 150
ClassicTDHealth = 150
Speed = 2.0
ClassicTDSpeed = 2.0
Range = 7.0
ProjectileTravelSpeed = 8.0
ProjectileMaxDistance = 8.0
Damage = 50

[Stats.Resistance]
Slow = 0.0
Stun = 0.0
Knockback = 0.0
Poison = 0.0