ModTarget = "Tower.Spinblade"

[Stats]
Cost = 2
ClassicTDCost = 10
Health = 300
Damage = 4
ClassicTDDamage = 4
Range = 1.0
MaxProjectiles = 0
ProjectileTravelSpeed = 0.0
ProjectileMaxDistance = 0.0

[Stats.Effects]
KnockbackAmount = 0.0
SlowAmount = 0.0
SlowDuration = 0.0