ModTarget = "Tower.Spinblade"

[Sprites]
Texture = "Spinblade.Sprites.png"
Width = 48
Height = 48

[Sprites.BaseSprites]
Base = 15

[Sprites.Animations]
Attack = "15-8"
Idle = "15-8"
Spawn = "1-7"

[Sprites.FrameDurations]
1 = 100
2 = 66
3 = 66
4 = 66
5 = 49
6 = 66
7 = 66
8 = 16
9 = 33
10 = 33
11 = 33
12 = 33
13 = 33
14 = 33
15 = 33