ModTarget = "Tower.Spike"

[Stats]
Cost = 1
ClassicTDCost = 5
Lifespan = 45
Damage = 10
ClassicTDDamage = 8
Range = 0.0
MaxProjectiles = 0
ProjectileTravelSpeed = 0.0
ProjectileMaxDistance = 0.0

[Stats.Effects]
KnockbackAmount = 0.0
SlowAmount = 0.0
SlowDuration = 0.0