ModTarget = "Configuration"
GameMode = "Campaign"

[Towers]
Axe = "1.1"
Bear = "1.1"
Chakram = "1.1"
Crossbow = "1.1"
FakeGoat = "1.1"
Flamethrower = "1.1"
Harpoon = "1.1"
Mortar = "1.1"
Punch = "1.1"
Scattershot = "1.1"
Solaris = "1.1"
Spike = "1.1"
Spinblade = "1.1"
Tar = "1.1"
Tesla = "1.1"
Zap = "1.1"
