ModTarget = "Enemy.TrollAssassin"

[Stats]
Health = 80
ClassicTDHealth = 40
Speed = 5.0
ClassicTDSpeed = 5.0
Range = 2.75
ProjectileTravelSpeed = 0.0
ProjectileMaxDistance = 0.0
Damage = 50

[Stats.Resistance]
Slow = 0.0
Stun = 0.0
Knockback = 0.0
Poison = 0.0