ModTarget = "Tower.Punch"

[Stats]
Cost = 2
ClassicTDCost = 7
Health = 300
Damage = 20
ClassicTDDamage = 20
Range = 1.0
MaxProjectiles = 0
ProjectileTravelSpeed = 0.0
ProjectileMaxDistance = 0.0

[Stats.Effects]
KnockbackAmount = 3.0
SlowAmount = 0.0
SlowDuration = 0.0