ModTarget = "Tower.Harpoon"

[Sprites]
Texture = "Harpoon.Sprites.Attack.png"
Width = 48
Height = 16

[Sprites.SpritePaths]
AttackUp = "Core"
AttackDown = "Core"
AttackLeft = "Core"
AttackRight = "Core"

[Sprites.Animations]
AttackDown = "9-17"
AttackLeft = "0-8"
AttackRight = "0-8"
AttackUp = "18-26"

[Sprites.FrameDurations]
9 = 1000
10 = 70
11 = 70
12 = 70
13 = 59
14 = 70
15 = 70
16 = 70
17 = 53
0 = 1000
1 = 70
2 = 70
3 = 70
4 = 59
5 = 70
6 = 70
7 = 70
8 = 53
18 = 1000
19 = 70
20 = 70
21 = 70
22 = 70
23 = 70
24 = 70
25 = 70
26 = 53