ModTarget = "Tower.Harpoon"

[Sprites]
Texture = "Harpoon.Sprites.Spawn.png"
Width = 64
Height = 64

[Sprites.Animations]
Spawn = "0-17"

[Sprites.FrameDurations]
0 = 59
1 = 59
2 = 59
3 = 60
4 = 59
5 = 60
6 = 60
7 = 60
8 = 59
9 = 60
10 = 60
11 = 60
12 = 60
13 = 60
14 = 60
15 = 60
16 = 60
17 = 483