ModTarget = "Enemy.GiantSpider"

[Stats]
Health = 90
ClassicTDHealth = 30
Speed = 2.5
ClassicTDSpeed = 2.5
Range = 1.0
ProjectileTravelSpeed = 0.0
ProjectileMaxDistance = 0.0
Damage = 15

[Stats.Resistance]
Slow = 0.0
Stun = 0.25
Knockback = 0.0
Poison = 0.0