ModTarget = "Tower.Mortar"

[Stats]
Cost = 2
ClassicTDCost = 12
Health = 200
Damage = 25
ClassicTDDamage = 25
Range = 9.0
MaxProjectiles = 0
ProjectileTravelSpeed = 7.0
ProjectileMaxDistance = 10.0

[Stats.Effects]
KnockbackAmount = 0.0
SlowAmount = 0.0
SlowDuration = 0.0