ModTarget = "Enemy.TrollBrute"

[Stats]
Health = 250
ClassicTDHealth = 140
Speed = 2.5
ClassicTDSpeed = 3.0
Range = 1.0
ProjectileTravelSpeed = 0.0
ProjectileMaxDistance = 0.0
Damage = 100

[Stats.Resistance]
Slow = 0.0
Stun = 0.699999988
Knockback = 0.75
Poison = 0.0