ModTarget = "Tower.FakeGoat"

[Stats]
Cost = 2
ClassicTDCost = 5
Health = 150
Damage = 100
ClassicTDDamage = 100
Range = -1.0
MaxProjectiles = 0
ProjectileTravelSpeed = 0.0
ProjectileMaxDistance = 0.0

[Stats.Effects]
KnockbackAmount = 0.0
SlowAmount = 0.0
SlowDuration = 0.0