ModTarget = "Tower.Tar"

[Stats]
Cost = 1
ClassicTDCost = 4
Lifespan = 45
Damage = 0
ClassicTDDamage = 0
Range = 0.0
MaxProjectiles = 0
ProjectileTravelSpeed = 0.0
ProjectileMaxDistance = 0.0

[Stats.Effects]
KnockbackAmount = 0.0
SlowAmount = 0.3
SlowDuration = 6.0