ModTarget = "Enemy.GnoblingDartSpitter"

[Stats]
Health = 45
ClassicTDHealth = 80
Speed = 2.0
ClassicTDSpeed = 3.0
Range = 7.0
ProjectileTravelSpeed = 6.0
ProjectileMaxDistance = 8.0
Damage = 20

[Stats.Resistance]
Slow = 0.0
Stun = 0.0
Knockback = 0.0
Poison = 0.0