ModTarget = "Enemy.TrollCyborg"

[Stats]
Health = 140
ClassicTDHealth = 110
Speed = 3.0
ClassicTDSpeed = 3.0
Range = 1.0
ProjectileTravelSpeed = 0.0
ProjectileMaxDistance = 0.0
Damage = 50

[Stats.Resistance]
Slow = 0.25
Stun = 0.0
Knockback = 0.5
Poison = 0.0