ModTarget = "Tower.Bear"

[Sprites]
Texture = "Bear.Sprites.png"
Width = 32
Height = 32

[Sprites.BaseSprites]
Base = 0

[Sprites.Animations]
Attack = "13-18,13"
Idle = "12,12,12,12"
Spawn = "0-9,11-12"

[Sprites.FrameDurations]
13 = 66
14 = 83
15 = 2816
16 = 83
17 = 83
18 = 49
12 = 316
0 = 66
1 = 66
2 = 66
3 = 66
4 = 66
5 = 66
6 = 66
7 = 66
8 = 66
9 = 66
11 = 66