ModTarget = "Tower.Bear"

[Stats]
Cost = 1
ClassicTDCost = 4
Lifespan = 45
Damage = 50
ClassicTDDamage = 40
Range = 0.0
MaxProjectiles = 0
ProjectileTravelSpeed = 0.0
ProjectileMaxDistance = 0.0

[Stats.Effects]
KnockbackAmount = 0.0
SlowAmount = 0.99
SlowDuration = 3.0