ModTarget = "Enemy.Necromancer"

[Stats]
Health = 80
ClassicTDHealth = 80
Speed = 2.0
ClassicTDSpeed = 2.0
Range = 7.0
ProjectileTravelSpeed = 0.0
ProjectileMaxDistance = 0.0
Damage = 0

[Stats.Resistance]
Slow = 0.0
Stun = 0.0
Knockback = 0.0
Poison = 0.0