ModTarget = "Enemy.TrollGrunt"

[Stats]
Health = 80
ClassicTDHealth = 110
Speed = 2.0
ClassicTDSpeed = 3.0
Range = 1.0
ProjectileTravelSpeed = 0.0
ProjectileMaxDistance = 0.0
Damage = 17

[Stats.Resistance]
Slow = 0.0
Stun = 0.0
Knockback = 0.2
Poison = 0.0