ModTarget = "Enemy.Salamander"

[Stats]
Health = 80
ClassicTDHealth = 80
Speed = 3.0
ClassicTDSpeed = 3.0
Range = 5.0
ProjectileTravelSpeed = 7.0
ProjectileMaxDistance = 6.0
Damage = 15

[Stats.Resistance]
Slow = 0.0
Stun = 0.0
Knockback = 0.0
Poison = 0.0