ModTarget = "Enemy.StormboltImp"

[Stats]
Health = 70
ClassicTDHealth = 70
Speed = 1.0
ClassicTDSpeed = 3.0
Range = 7.0
ProjectileTravelSpeed = 5.0
ProjectileMaxDistance = 8.0
Damage = 30

[Stats.Resistance]
Slow = 0.0
Stun = 0.0
Knockback = 0.0
Poison = 0.0