ModTarget = "Enemy.LilSlime"

[Stats]
Health = 15
ClassicTDHealth = 15
Speed = 1.5
ClassicTDSpeed = 1.5
Range = 1.0
ProjectileTravelSpeed = 0.0
ProjectileMaxDistance = 0.0
Damage = 10

[Stats.Resistance]
Slow = 0.0
Stun = 0.0
Knockback = 0.0
Poison = 0.0