ModTarget = "Enemy.TrollSapper"

[Sprites]
Texture = "TrollSapper.Sprites.png"
Width = 48
Height = 48

[Sprites.Animations]
AttackDown = ""
AttackLeft = ""
AttackRight = ""
AttackUp = ""
DieDown = "12-13"
DieLeft = "12-13"
DieRight = "12-13"
DieUp = "12-13"
HitDown = "18"
HitLeft = "16"
HitRight = "16"
HitUp = "17"
IdleDown = "18"
IdleLeft = "16"
IdleRight = "16"
IdleUp = "17"
WalkDown = "0-3"
WalkLeft = "4-7"
WalkRight = "4-7"
WalkUp = "8-11"
Zapped = "14-15"

[Sprites.FrameDurations]
12 = 100
13 = 83
18 = 83
16 = 83
17 = 83
0 = 100
1 = 100
2 = 100
3 = 83
4 = 100
5 = 100
6 = 100
7 = 83
8 = 100
9 = 100
10 = 100
11 = 83
14 = 83
15 = 66