ModTarget = "Enemy.TrollSapper"

[Stats]
Health = 80
ClassicTDHealth = 80
Speed = 4.0
ClassicTDSpeed = 4.0
Range = 1.0
ProjectileTravelSpeed = 0.0
ProjectileMaxDistance = 0.0
Damage = 250

[Stats.Resistance]
Slow = 0.0
Stun = 0.0
Knockback = 0.0
Poison = 0.0