ModTarget = "Enemy.GnoblingGuard"

[Stats]
Health = 80
ClassicTDHealth = 110
Speed = 1.5
ClassicTDSpeed = 3.0
Range = 1.0
ProjectileTravelSpeed = 0.0
ProjectileMaxDistance = 0.0
Damage = 15

[Stats.Resistance]
Slow = 0.0
Stun = 0.0
Knockback = 0.0
Poison = 0.0