ModTarget = "Tower.Chakram"

[Sprites]
Texture = "Chakram.Sprites.Attack.png"
Width = 48
Height = 16

[Sprites.SpritePaths]
AttackUp = "Core"
AttackDown = "Core"
AttackLeft = "Core"
AttackRight = "Core"

[Sprites.Animations]
AttackDown = "8-15"
AttackLeft = "0-7"
AttackRight = "0-7"
AttackUp = "16-23"

[Sprites.FrameDurations]
8 = 83
9 = 83
10 = 83
11 = 333
12 = 83
13 = 83
14 = 83
15 = 83
0 = 83
1 = 83
2 = 83
3 = 333
4 = 83
5 = 83
6 = 83
7 = 83
16 = 83
17 = 83
18 = 83
19 = 333
20 = 83
21 = 83
22 = 83
23 = 83