ModTarget = "Tower.Chakram"

[Sprites]
Texture = "Chakram.Sprites.Spawn.png"
Width = 48
Height = 48

[Sprites.Animations]
Spawn = "0-13"

[Sprites.FrameDurations]
0 = 66
1 = 66
2 = 66
3 = 66
4 = 66
5 = 66
6 = 66
7 = 66
8 = 66
9 = 66
10 = 66
11 = 66
12 = 66
13 = 66