ModTarget = "Tower.Flamethrower"

[Stats]
Cost = 2
ClassicTDCost = 10
Health = 200
Damage = 6
ClassicTDDamage = 6
Range = 3.0
MaxProjectiles = 1
ProjectileTravelSpeed = 0.0
ProjectileMaxDistance = 3.0

[Stats.Effects]
KnockbackAmount = 0.0
SlowAmount = 0.0
SlowDuration = 0.0