ModTarget = "Enemy.OgreSkullsplitter"

[Stats]
Health = 300
ClassicTDHealth = 300
Speed = 1.0
ClassicTDSpeed = 2.0
Range = 1.0
ProjectileTravelSpeed = 0.0
ProjectileMaxDistance = 0.0
Damage = 200

[Stats.Resistance]
Slow = 0.0
Stun = 0.2
Knockback = 1.0
Poison = 0.0