ModTarget = "Enemy.Slime"

[Stats]
Health = 30
ClassicTDHealth = 30
Speed = 1.5
ClassicTDSpeed = 1.5
Range = 1.0
ProjectileTravelSpeed = 0.0
ProjectileMaxDistance = 0.0
Damage = 15

[Stats.Resistance]
Slow = 0.0
Stun = 0.0
Knockback = 0.0
Poison = 0.0