ModTarget = "Enemy.GnoblingSpearman"

[Stats]
Health = 60
ClassicTDHealth = 80
Speed = 3.0
ClassicTDSpeed = 3.0
Range = 1.0
ProjectileTravelSpeed = 0.0
ProjectileMaxDistance = 0.0
Damage = 12

[Stats.Resistance]
Slow = 0.0
Stun = 0.0
Knockback = 0.0
Poison = 0.0