ModTarget = "Enemy.TrollGrenadier"

[Stats]
Health = 40
ClassicTDHealth = 30
Speed = 2.0
ClassicTDSpeed = 2.0
Range = 5.0
ProjectileTravelSpeed = 3.0
ProjectileMaxDistance = 10.0
Damage = 40

[Stats.Resistance]
Slow = 0.0
Stun = 0.0
Knockback = 0.0
Poison = 0.0