ModTarget = "Enemy.Observer"

[Stats]
Health = 500
ClassicTDHealth = 300
Speed = 3.0
ClassicTDSpeed = 1.0
Range = 7.0
ProjectileTravelSpeed = 20.0
ProjectileMaxDistance = 8.0
Damage = 10

[Stats.Resistance]
Slow = 0.0
Stun = 0.0
Knockback = 0.0
Poison = 0.0