ModTarget = "Enemy.Shrublin"

[Stats]
Health = 30
ClassicTDHealth = 30
Speed = 2.0
ClassicTDSpeed = 2.0
Range = 1.0
ProjectileTravelSpeed = 0.0
ProjectileMaxDistance = 0.0
Damage = 10

[Stats.Resistance]
Slow = 0.0
Stun = 0.0
Knockback = 0.0
Poison = 0.0