ModTarget = "Configuration"
GameMode = "Campaign"

[Artifacts]
Boomerang = "1.1.2"
Boots = "1.1.2"
Warhammer = "2.2.0"
Shield = "3.1.1"
Chainmail = "3.3.5"
FireBoots = "4.1.0"
Pickaxe = "4.1.14"
Boomeraxe = "5.1.0"

[PowerStones]
0 = "0.0.0"
2 = "1.1.2"
4 = "1.1.6"
5 = "1.2.3"
6 = "1.3.0"
7 = "4.4.1"
8 = "5.6.0"

[Towers]
Spinblade = "1.1.2"
Crossbow = "1.2.0"
Tar = "1.2.2"
Spike = "1.4.7"
Scattershot = "2.1.3"
Axe = "2.3.1"
Bear = "3.2.1"
Mortar = "3.3.1"
Punch = "3.4.1"
Tesla = "4.1.2"
Harpoon = "4.2.1"
Zap = "4.3.1"
Chakram = "4.5.1"
Flamethrower = "5.1.2"
FakeGoat = "6.2.1"
Solaris = "6.3.0"